### ISSUE TITLE
Improving file links

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Wiki#10]
When using "directory" icon at end of "File Link" edit field to link to a file that is in same directory as TaskList, or in subdirectory, the file name is relative to TaskList.
When dropping the same file link from Windows Explorer, the file name is absolute.

Enhancement: make the file name relative to TaskList everytime it is possible

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#3
