### ISSUE TITLE
HMS format truncates to HhMm

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Wiki#11]
_From @abstractspoon on July 14, 2015 2:3_

_From @abstractspoon on July 13, 2015 9:0_

_From @TonyGravagno on July 12, 2015 9:18_

**Tools > Preferences > User Interface > Tasklist Attributes> Date/Time Formatting >**
**"Display 'Estimated/Spent' times in HMS format"**

The fields actually look like 2h14m. There is no seconds value. When I see "HMS format" I think HH:MM:SS.

I looked into this option because I was thinking some project types might actually want timing down to the second. Then I thought the real goal was simply to show 1h30m rather than 1.5h.

So if seconds aren't a factor should the "S" be removed?

Or Is it a bug that seconds are not displayed?

To take this further, if a task is estimated at 50 hours, where 1 day = 8 hours and one week = 5 days, then the value displayed is "1w1d". So the hours get trimmed off here like seconds are trimmed above. And large hour values return values like 2y5m with days truncated.

So is it consistent and expected that the least significant units are removed? (They are not rounded.)

Is it assumed that as the values get larger that the details become less important - so 2y5m3d2h9m becomes ridiculous as a project estimate? If this is the case (and I'd agree), I'm wondering if the values should be rounded up rather than truncated. And does this same logic apply to time spent where actual time might be more significant than a rounded estimate?

_Copied from original issue: abstractspoon/ToDoList_Resources#11_

_Copied from original issue: abstractspoon/ToDoList_Wiki#2_

_Copied from original issue: abstractspoon/ToDoList_Issues#10_

**Comment by abstractspoon** [comment]
As you have pointed out, the point of this format was to hide insignificant information only.

I also realise that **HMS** is not strictly correct but it still best describes what you are going to get. And anything else risks confusing the user further.

I'm open to increasing the significant 'elements' to 3 in 7.1 but I don't feel it's very high priority.

**Comment by TonyGravagno** [comment]
I propose this issue get moved back to _Issues. It's a question/issue on the software, not the wiki. We can flag _Issues with a new label "wiki" so that we know something in the ticket should prompt a wiki update, as this one does.

**Comment by abstractspoon** [comment]
I hear you, but that leaves unresolved the question of **where do people ask questions about using the software**?

**Comment by TonyGravagno** [comment]
For the software: Questions, Bugs, and Enhancements all go to _Issues.
Questions about the wiki go to _Wiki, bugs with the wiki go to _Wiki, enhancements to the wiki to _Wiki.

**Comment by abstractspoon** [comment]
I think this would be a mistake because it means that the legitimate bug reports are going to get lost in a sea of questions. I think we need a better plan than this...

**Comment by abstractspoon** [comment]
ps. Remember too (and perhaps more importantly) that most people coming to the wiki will neither have GH accounts nor will they need them to view the wiki. You can't possibly force these people into creating a GH account just to ask a simple question. That policy will drive people away and hurt the software.

**Comment by TonyGravagno** [comment]
I don't like the idea of general enquiries being in an issue tracker anyway. I'd suggest all questions should be referred to CP, but people need an account there to post as well. This is why I suggested a Google Group. Most people who do anything on the internet have a GMail account anyway. And with GG we can block anyone who abuses the environment. (And we should be having this discussion somewhere else too but I don't think anyone cares. LOL)

**Comment by TonyGravagno** [comment]
I'm assigning this ticket to myself to ensure the wiki communicates the usage of the HMS format. The Google Group has been setup to join CP for questions. We can pursue that topic elsewhere.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#27
