### ISSUE TITLE
GettingHelp link

### ISSUE THREAD

**Issue by Simplenuity** [abstractspoon/ToDoList_Wiki#13]
"To find anything from files, issues, or documentation, or to report issues, please see GettingHelp which has links to everywhere else."

GettingHelp is taking me to:
[https://github.com/abstractspoon/ToDoList_Wiki/wiki/GettingHelp] (https://github.com/abstractspoon/ToDoList_Wiki/wiki/GettingHelp)
This link doesn't show any content anymore but offers to "Create new page".

The page I was expecting has the following URL:
https://github.com/abstractspoon/ToDoList_Wiki/wiki/Getting-Help

Typo or on purpose?

**Comment by Simplenuity** [comment]
Just found the page I was expecting with the following URL
[https://github.com/abstractspoon/ToDoList_Wiki/wiki/Getting-Help] (https://github.com/abstractspoon/ToDoList_Wiki/wiki/Getting-Help)

Type or on purpose?

**Comment by abstractspoon** [comment]
I noticed this too.

Tony: The problem seems to be that when you change the title of a page to include spaces, GH inserts dashes between the words thus changing the URL of the page.

**Comment by TonyGravagno** [comment]
I actually made that change yesterday, sorry. All pages that were CasedLikeThis were Renamed-Like-This. The reason is so that the header of the pages would show as "Word1 Word2" rather than an awkward "Word1Word2". Sorry about the confusion but with a new site I figured it wouldn't be that bad to do some shifting around. Please change any links that go to Word1Word2 pages. There weren't many. Thanks!

**Comment by abstractspoon** [comment]
I don't seem to be getting notified of all your changes. Any ideas why that might be?

**Comment by Simplenuity** [comment]
Dan, I assume you're talking about my changes?
No idea what's going on. First time I have ever used GitHub, so still finding my way around it.
Will have a look in my settings.
Ryan

**Comment by abstractspoon** [comment]
Perhaps the notifications only refer to the Repo files...

Rgds, .dan.g.

www.abstractspoon.com

**Comment by Simplenuity** [comment]
Tony, I can't seem to edit/correct the link on the README.md pages of each repository. Am I missing something?
Ryan

**Comment by TonyGravagno** [comment]
@Simplenuity, maybe there are contributor-specific privileges? Not sure. I'll hit the ReadMe and other pages as time permits. In the meantime GettingHelp now has an apology with a link.

@abstractspoon, if you mean wiki changes, subscribe via [RSS/Atom](https://github.com/abstractspoon/ToDoList_Wiki/wiki.atom). I get all notifications by email in my Outlook folder under RSS Feeds. It's quite convenient. 

I guess I closed this ticket prematurely, re-opening.

**Comment by Simplenuity** [comment]
Haven't found out about contributor-specific privileges yet.
The diverting page for old GettingHelp links is a great interim solution till all links get updated.

on a side note: If you come across a pure email notification for Wiki changes, please let me know. Am not using RSS/Atom.

**Comment by TonyGravagno** [comment]
About RSS, just click that link you'll get an option to subscribe from your browser. So just check your subscriptions and you'll see whatever has changed. Again, I see the RSS just like emails in Outlook. And there are services that will email you whenever a change has been made to an RSS page.
