### ISSUE TITLE
ToDoList Version 7 German translation isn't correct

### ISSUE THREAD

**Issue by Stefan112** [abstractspoon/ToDoList_Wiki#17]
German Translation in Version 7 have many issues. The German letters ä ,ü ,ö and so on are not in the wright version.

Thanks

Stefan

**Comment by Pierre-de-la-Verre** [comment]
Should be already solved in the updated download package. Please take a look here:
https://github.com/abstractspoon/ToDoList_Issues/issues/39

**Comment by Stefan112** [comment]
Thanks, work great !!! Thanks for the wonderful program

**Comment by TonyGravagno** [comment]
Please post translation issues to the repo for [Resources](https://github.com/abstractspoon/ToDoList_Resources). But thanks for visiting the wiki. Tschüß!
