### ISSUE TITLE
Unselect multiple selection

### ISSUE THREAD

**Issue by andrewculda** [abstractspoon/ToDoList_Wiki#18]
Just upgraded ToDoList to ver.7 and I noticed that when I'm selecting multiple tasks (whether consecutive or not), I cannot unselect that group by selecting a single item from that selected group; instead, i must select a different task that is not part of the selected group. Is that a bug or?
I'm on Win7Pro.

**Comment by Pierre-de-la-Verre** [comment]
Are you sure that this is a topic for the "Wiki"? Maybe it is better placed in the "Issues"
https://github.com/abstractspoon/ToDoList_Issues
or in the forum?

**Comment by andrewculda** [comment]
Right. Sorry, new around here.
