### ISSUE TITLE
Page "User Defined Tools Preferences"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#20]
Please add a description of the "Import..." button.

**Comment by TonyGravagno** [comment]
Until a wiki page is created, please see [this forum post](http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-o?msg=5114189#xx5114189xx)

**Comment by Pierre-de-la-Verre** [comment]
Closed because of new Wiki-page.
