### ISSUE TITLE
Archiving TDL entries / subtrees

### ISSUE THREAD

**Issue by fwornle** [abstractspoon/ToDoList_Wiki#21]
Would it be possible to enhance the archiving functionality of TDL by allowing archiving to be done in the following way?

- the selected task and all of it's sub-tasks are copied from the original TDL to a new TDL called **SOMEFILENAME.done.tdl** (as presently done)
- they are removed from the original TDL (as presently done)

**However:**
- in the original TDL, the selected (top-level) task is retained and a link added to the corresponding item in the archive file
- the task is marked as "done" (checkbox/status)
- this behavior of "archiving" should be optional, i. e. configurable via a new option in preferences

**Comment by Pierre-de-la-Verre** [comment]
Hi fwornle

I'm not sure if the Wiki is the best place to discuss a new suggestion. Maybe the forum at Codeproject would be better?

**Comment by fwornle** [comment]
Hi Peter,

I agree - I meant to post an 'enhancement request'... didn't realize that I posted this on the wiki. Sorry. Should I re-post this somewhere else? I'll try to find the 'CodeProject' then...

Kind regards,
Frank

**Comment by Pierre-de-la-Verre** [comment]
The "codeproject" is here:
http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-on

It is the main site of TDL since it started. The Github-Environment was started some weeks ago and is under development: "open discussions" should be posted on Codeproject.

If it is OK for you then please "close" this issue.

**Comment by TonyGravagno** [comment]
Let's leave this open. Dan might move it to the Issues repo. I think this is related to [another](https://github.com/abstractspoon/ToDoList_Issues/issues/40) open request.

You're welcome to post suggestions or bugs related to the software to the [Issues repo](https://github.com/abstractspoon/ToDoList_Issues/issues), but yes, this tracker here is just for the Wiki. Thanks.

**Comment by fwornle** [comment]
Thanks. Will do.

Frank.

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#56
