### ISSUE TITLE
Possibility to make a project a template and to open such a template

### ISSUE THREAD

**Issue by Stoffe** [abstractspoon/ToDoList_Wiki#22]
Add the possibility to save a project as a template and then when creating a new project, create a new project from such a template.
This is good when you have specific projects wich is thoughtthru and you dont wanna miss anything.
You make such a template, then when you create a new project of this type (please note, there can be different types of templates depending on the type of project you have at the moment)
Some project categories or tasks or both are allready created.

Of course, you can save theese templates at a central location so all that is using ToDoList can open such a template and use it. (On the local network I mean of course)

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#63
