### ISSUE TITLE
General comment about the whole project

### ISSUE THREAD

**Issue by Stoffe** [abstractspoon/ToDoList_Wiki#24]
There is a possibility to add a comment on tasks and categories.
However Im missing the possibility to add a general comment about the whole project.
Like, describing the project or to make a comment that all who opens this project will read.
There is the small line on top to describe your project, but sometimes you need to write more than that. :/

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#61
