### ISSUE TITLE
ToDoList and MS OneDrive

### ISSUE THREAD

**Issue by abstractspoon** [abstractspoon/ToDoList_Wiki#31]
_From @abstractspoon on July 14, 2015 1:23_

I’ve recently moved my TDL files from DropBox to MS OneDrive. When saving (Ctrl-S) a Task List to a folder on OneDrive I often (50% of the time) see the following error pop-up.

![image001](https://cloud.githubusercontent.com/assets/12944354/8664444/af70c4f4-2a1a-11e5-8955-303459895599.png)

I’m the only one modifying the Main.tdl file. It seems that OneDrive sets an attribute on the Main.tdl file after uploading it to the cloud and this causes TDL to believe someone else modified the file from another copy of TDL.

For now, I’ve just disabled timestamp checking in TDL, so I’m not impacted by this issue. Could just be a bug in OneDrive for all I know, but I thought I’ll report this potential issue anyway.

![image004](https://cloud.githubusercontent.com/assets/12944354/8664428/847b115a-2a1a-11e5-8b4c-1e8e189dfa5b.jpg)

 The following is a minor issue, but a space (“ “) is missing after the “.” In the message below. Should read “… outside of TodoList. Would …” instead of “… outside of TodoList.Would …”

![image005](https://cloud.githubusercontent.com/assets/12944354/8664423/78bdebf8-2a1a-11e5-9c6c-6a1449a3ce3e.png)

_Copied from original issue: abstractspoon/ToDoList_Issues#1_

**Comment by abstractspoon** [comment]
_From @TonyGravagno on July 20, 2015 21:1_

If this behaviour with OneDrive or any other cloud service is not a bug, but consistent with how things are expected to work, then I'll add this info to the wiki.

For now, I've already flagged this ticket with the new Wiki label. Please use that when appropriate even if just to draw attention to a ticket where better documentation might help.

**Comment by abstractspoon** [comment]
I have investigated this fairly simplistically by installing OneDrive and trying to reproduce the error but without any luck.

I'm assigning it to Tony for now to add to the wiki.

**Comment by abstractspoon** [comment]
_From @TonyGravagno on August 1, 2015 1:10_

Wiki [File Menu](https://github.com/abstractspoon/ToDoList_Wiki/wiki/FileMenu) page updated with this note under **Save Tasklist** :

> Note: :warning: When saving a tasklist to a remote server like OneDrive or DropBox,
> it's possible for a TimeStamp Change warning to display. See [this issue report](/abstractspoon/ToDoList_Issues/issues/1) for
> information about what causes this and how to avoid the warning.

**Comment by wfouche** [comment]
Hi @abstractspoon 

I originally reported this issue via email. Not seeing this issue with OneDrive anymore. Could just have been something transient.

This issue can be closed.

Thanks,

Werner
