### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Gert1959** [abstractspoon/ToDoList_Wiki#32]
Hi,

I wanted to post some issues for ToDoList. After Following your Link "guidelines for contributing" I got the page https://github.com/abstractspoon/ToDoList_Wiki/blob/master/CONTRIBUTING.md. But the link under "Software issues get reported here" led to an error 404.

Regards
Gert

**Comment by TonyGravagno** [comment]
Thanks for your note. We recently got rid of the Issues repo. The CONTRIBUTING page has been updated.
