### ISSUE TITLE
Task Comments, Simple Text mode, cut-n-paste errors

### ISSUE THREAD

**Issue by vulpineblaze** [abstractspoon/ToDoList_Wiki#33]
##Background:

I use the "Task Comments" feature extensively, and have been vexed my this issue for quite some time.
I use "Simple Text" mode, and anything I cut-n-paste into this area is intended to be text-only, no fonts or formats and hyperlinks, etc..

##The problem is this: 

Most of the text I cut-n-paste does come from other places that are rich-text, or HTML, etc..  And instead of stripping the format, like Notepad or Sublime would do, I get weird little artifacts, like "( about:blank )" instead of the text I expect. 

##Desired outcome:

I would like when cut-n-paste'ing into the Task Comment, while in Simple Text mode, for the pure text to remain, and all formatting and artifacts be removed. I don't need links or fonts or pictures in Simple Text mode, and I don't believe anyone else does either.

##Example:

My company uses an instant messenger program (MS Office Communicator 2007R2), and my co-workers and I frequently resolve issues using this program. I would like to cut-n-paste snippets of text from there to ToDoList, so I can reference it. 
Instead, I get this ( about:blank ), and nothing else. This is one of many programs that leave these artifacts and/or lose text. 
So, I usually Ctrl+V, Ctrl+A, Ctrl+X in Notepad to get only the text (Notepad & Sublime paste the text only) and then paste the output from Notepad into ToDoList, which will now work as intend, with only the text appearing.

**Comment by Pierre-de-la-Verre** [comment]
hi
this place - abstractspoon/ToDoList_Wiki - is not the right place for common issues. For discussions and questions please use http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-on. for reporting of a bug please use https://groups.google.com/forum/#!forum/abstractspoon-todolist-support.
Please close this issue here.

**Comment by TonyGravagno** [comment]
@vulpineblaze Thanks for your suggestions but as @Pierre-de-la-Verre said, change requests aren't processed here. Please see the [Getting Help](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Getting-Help) page and create a post in the Google Group. I'd happily post your note to the group myself but then Dan wouldn't be able to follow-up with you. I'll close this ticket on your confirmation. Thanks.

**Comment by vulpineblaze** [comment]
I have posted in the google group.
