### ISSUE TITLE
No longer possible to complete multiple tasks.

### ISSUE THREAD

**Issue by abones** [abstractspoon/ToDoList_Wiki#34]
Hello.

I've recently updated to ToDoList 7.0 and noticed that now you cannot mark all of the selected tasks as 'Completed'.

What I did:
1. Had several recurrent tasks with 'Re-use' option enabled (non-recurrent tasks work fine)
2. Selected them (via Shift+Click)
3. Clicked on an item in 'Completion Checkbox' column

No tasks are checked after that; in previous releases, however, this marked all tasks as completed.

**Comment by Pierre-de-la-Verre** [comment]
Please post bug reports and problem to

the forum: http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-on
or to
the Google Group: https://groups.google.com/forum/#!forum/abstractspoon-todolist-support

I will close this "issue" here.

Thanks for understanding.
