### ISSUE TITLE
No way to copy Task Link without checking out the todolist (7.0.6)

### ISSUE THREAD

**Issue by Schack17** [abstractspoon/ToDoList_Wiki#35]
Since Version 7 I can not copy the link in a task without checking out the todolist from version control.
In Version 6.x works this.
Please re enable it. Thanks.

**Comment by TonyGravagno** [comment]
When you click "New Issue" there is a message that says:

> Please review the guidelines for contributing to this repository.

Please see the guidelines and report the issue in the Google Group. Thanks.
