### ISSUE TITLE
Documentation on fixing time tracking errors

### ISSUE THREAD

**Issue by rjgenik** [abstractspoon/ToDoList_Wiki#39]
I'm looking for a help file that shows how I can fix an error in time tracking. I left the Time Tracker running for several hours after I left my office and returned. I need to fix the stop point for that log entry. I have tried editing the latest .csv file in Excel and notepad. The changes I make don't appear when I reopen the program. 

How do I change the task list logs to correct mistakes?

timelogerror

**Comment by TonyGravagno** [comment]
I will certainly add this information to the wiki when possible. There are still a lot of gaps, nothing forgotten, just no time to actually write up the docs properly.

To answer your question:

Focus on a task.
Right click and go to Other Task Attributes
Then to Add Time To Task Log File.
(Or I believe the default to get there is Ctrl-Alt-Shift-A)

Now you can add positive or negative time spent to the time that's already logged.
There is a prompt here to "Also add time to task's time spent"

ToDoList stores the summary time for each task in the .tdl file, and the detail is in the .csv time log file. If you've already modified the .csv file, there's no need to re-do it. You can add or remove time and uncheck that box.

I leave the clock on too. My solution is to look at the last logged time, then completely reverse it out using a negative time entry (checking to update the log). I add a comment that this is a correction. Then I click Apply. Now I enter a positive amount for the actual time spent. The Time field is the END time of the transaction. With a negative "credit" and positive "debit" the time balance is then accurate, and there is a clear record that an error was but but that it was corrected. This is better than manually fudging the numbers..

Finally, while this is a good report to add this info to the wiki, please ask questions in the Google Group, as there is a much better chance of getting quick answer there.

Thanks for the report. I'm assigning it to myself for processing.

**Comment by rjgenik** [comment]
Hi Tony,
Thanks, that solution worked great.
I agree that it is better to wipe out the whole entry and add back the correct time, using the correction time as the entry time (keep everything reproducible). 
BTW, I would have asked on Google Groups (if my Google id still works... haven't used it in a while) but the Help/Online Documentation menu item took me to Github (where I do have an active account). I didn't see a Google Groups link from GitHub or mentioned in the Help Menu.
Cheers,
Rich

**Comment by TonyGravagno** [comment]
In ToDoList, see menu>Help>Feedback and Support. That gets you to the Google Group. There's not a lot of room there to say Feedback and Support via Google Groups. Dan (@abstractspoon) might see this and make a change there.

From menu>Help>Online Documentation, is the [Getting Help](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Getting-Help) page which has links to all resources.

At the bottom of every page on the wiki is this line which also links back to the Getting Help page:
"If you need help finding anything, go [here](https://github.com/abstractspoon/ToDoList_Wiki/wiki/Getting-Help)."

At the top of the page when entering a new Issue here is this announcement:
"Please review the [guidelines for contributing](https://github.com/abstractspoon/ToDoList_Wiki/blob/master/CONTRIBUTING.md) to this repository."
On that page is some large text, and a few links to help.

I welcome you (and all others) to click around to become familiar with the available resources.

HTH
