### ISSUE TITLE
User defined tools - Add icon

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#40]
As "Icon" for user defined tools I can select what I want - ico, exe, png, bmp, .. - but mostly it does not make sense, because PNG and BMP are not used (only the icon which displays that it is a BMP/PNG), from exe is takes only the main(?) icon, ....
Please give a more precise description of this comamnd.

**Comment by TonyGravagno** [comment]
@Pierre-de-la-Verre I was going to flag your Google thread to trigger a wiki update. However, I'm confused about what you're asking. If the software does not yet allow different icon types, I can't update the wiki with that yet. And when you say "precise description of this command" - which command are you talking about? Do you mean in general how to assign the icon from some exe to a UDT?

And is (this)[https://github.com/abstractspoon/ToDoList_Wiki/wiki/User-Defined-Tools-Preferences#icon] the content that you'd like to see enhanced?

Thanks.

**Comment by abstractspoon** [comment]
The issue that the 3rd party tool dialog allows __any__ file to be specified for the icon including image files but only works if an executable file is selected is a bug.

Peter may be suggesting that this subtlety be added to the wiki until such time as I can fix it.

**Comment by Pierre-de-la-Verre** [comment]
> Peter may be suggesting that this subtlety be added to the wiki until such time as I can fix it.

Yes, that’s what I want to say.

 

Peter

**Comment by TonyGravagno** [comment]
Got it.

**Comment by Pierre-de-la-Verre** [comment]
Closed because of new Wiki-page.
