### ISSUE TITLE
"Time Tracking"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#41]
This page is missing the manual modifications:
- add time via dialogue (pos. and neg. values)
- modify the time value in the edit field

These manual features enlarge the functionality from pure "tracking" to (a little bit) "managing".

Also you could refer to some relating settings in "preferences".

**Comment by TonyGravagno** [comment]
Good suggestions. I'll make it happen. Thanks!

**Comment by Pierre-de-la-Verre** [comment]
Closed because of new Wiki-page.
