### ISSUE TITLE
Keyboard usage inside edit fields

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#42]
## Maybe the info from this discussion can be useful:

Is it possible, to enter a new task and select/insert additional data (like Priority, Due Date, Status, ...) using the tab-key?
I know that you can use e.g. alt-y to access Priority. But wouldn't it be far nicer/smoother, to tab through the options and dropdowns? 

> > mouse-interaction is in any cause needed to fill in Due Date and select Category 

Not so Joey. 
1. When the focus is on a date field, the spacebar will drop-down the calendar
2. When the focus is on a multi-selection combobox, Alt+spacebar drops-down the list and Ctrl+spacebar selects/deselects individual items.

...indeed a popup (optional?) would be very nice and would enhance user experience, I think. 

@Pierre: tab works partially for me. I still have to check that I can reproduce occurrences when tab does nor work.
However, mouse-interaction is in any cause needed to fill in Due Date and select Category (due to the multiple chioce option).

...
Are you asking for a popup dialog where all the attributes are presented for easier initial entry?

[Discussion here](https://groups.google.com/d/msg/abstractspoon-todolist-support/2eCW9n0C6K4/pSAhA5oIBAAJ)

**Comment by TonyGravagno** [comment]
Thanks. I've trimmed down the request and set the link to the original discussion. I was going to see where that discussion went and then flag it for Wiki Change Suggested. I just did that and when I go through the forum looking for wiki topics I'll be sure to get that with the others. I'll close this when I eventually incorporate the notes into the wiki.

**Comment by Pierre-de-la-Verre** [comment]
Closed because of new Wiki-page.
