### ISSUE TITLE
User Defined Tools Preferences - description of userdate / -text / -folder ...

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#43]
It seems that the values "userdate / -text / -folder / -file" have a special feature /  behaviour / format? What to the do? What happens if I mix them up?

**Comment by TonyGravagno** [comment]
I'm not familiar with any of those terms. I don't see "userdata" in the CP forum. Can you tell me exactly where you are getting your information? Written on the page? Forum? Email? Code?
"userdata" ?   "-text" ?  "-folder" ?  "-file" ?

**Comment by TonyGravagno** [comment]
I changed your term "userdata" to "userdatE".The documentation you seek is on the (https://github.com/abstractspoon/ToDoList_Wiki/wiki/User-Defined-Tools-Preferences)[UDT Preference page.] Search on that page for "User Date". That's literal text "userdate". Casing doesn't seem to be important "userDate", "UserFile", etc. The text in the $(arguments) is not enclosed in quotes. See info on Placeholders and examples. Does that respond to your enquiry?

**Comment by Pierre-de-la-Verre** [comment]
Yes, I meant "userdate". 
It could be helpful to describe that the usage of these terms invokes different dialogue: one text field  / date-field plus calendar / select folder menu / select file menu.

**Comment by TonyGravagno** [comment]
Will do, and will get screenshots. Thanks!

**Comment by Pierre-de-la-Verre** [comment]
Closed because of new Wiki-page.
