### ISSUE TITLE
Formatting of long text chapters

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#44]
Hi Tony
for example the chapter "File Menu" (and others) are a lot of text (plus some "Notes"). I tried some simple formatting - see attachment. What's your opinion?

Peter

[Editing FileMenu · abstractspoon-ToDoList_Wiki Wiki.zip](https://github.com/abstractspoon/ToDoList_Wiki/files/99948/Editing.FileMenu.abstractspoon-ToDoList_Wiki.Wiki.zip)

**Comment by TonyGravagno** [comment]
:+1:  I completely agree with all of your suggestions. I haven't been focused so much on consistent formatting, more on content and then basic formatting. That specific page was imported from the old wiki and then just touched up with a bit of simple formatting and some content. There was never an intent on that page (so far) to apply any form of "styling", just formatting.

I haven't defined a set of conventions for consistent styling. I try to be consistent within a document, and sometimes I'll look at others to see how they were formatted. So there are certainly differences like whether pages have H3 or H4 or just bold text for sub-headers. I try to let the content of each document drive the styling - though of course that's not ideal.

I would welcome a definition document with a clear spec for what markdown to use for specific kinds of content. I would certainly follow it. Unfortunately, markdown and basic HTML doesn't lend itself to true styling, at least not until HTML5. Relying on styling to indicate meaning is a bad practice. We can't say [subheader] and define a style based on content, we can only define the visual format: H1, H2, Bold, Italic, etc. The solution to that is to use CSS, but that's not supported here. Ultimately the best thing for "site-wide" consistency is to use MediaWiki or WordPress, or something else that allows CSS.

So those are all of my thoughts on this. How would you like to proceed?

Note: I have the wiki cloned to my PC and I do periodic commits/pushes. (Unfortunately not frequent but I should...) So if you'd like to modify some pages, let's coordinate in email to ensure there's no duplication or lost work.

Also, FWIW, after looking around for various tools, I've been using [Haroopad](http://pad.haroopress.com/user.html) for editing markup off-line. And I've been trying other markup editors over Android - for those times when I'm stuck somewhere with nothing to do but write documentation. :dizzy_face: All docs are synced to my DropBox and I push to GitHub from there.

**Comment by Pierre-de-la-Verre** [comment]
Hi Tony

 

in my document I didn’t want to make special suggestions, I tried only different formattings (there are not so many in markdown ...).

 

Personally I don’t have a preference (list or bold or italic  ..) and I’m not talented in grafic design, but yes – it should be defined in a document. Will you do it?

 

Pierre

**Comment by TonyGravagno** [comment]
Yes. I'd like to focus on content primarily and I'm sure there won't be any conventions to start, but as more content is added I'll do what I can to establish and implement a consistent styling. Thanks for the feedback. Leaving this open for later follow-up.

**Comment by Pierre-de-la-Verre** [comment]
Closed because of new Wiki-page.
