### ISSUE TITLE
Internal support for protocol handlers

### ISSUE THREAD

**Issue by j-xella** [abstractspoon/ToDoList_Wiki#46]
TodoList already does a good job at protocol handlers, offering to register a handler if one is not present. However, sometimes it is simply not possible (corporate network with limited user privileges). In such case, it would be great if it would be possible to register protocol handler internally in TodoList.

When clicking on a URL, todolist would first check internal protocol handlers and, if not there, pass it on to Windows.

**Comment by TonyGravagno** [comment]
Thanks for the suggestion. However, this is the tracker for the Wiki / Documentation and not for the software. Please see the [Getting Help](../wiki/Getting-Help) page which will point you to CodeProject and the Google Group.

Closing this ticket and hoping you will re-open a discussion in one of the other sites.
