### ISSUE TITLE
Google Groups: Info: How to use this forum!!

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [abstractspoon/ToDoList_Wiki#47]
Not related to the Wiki, but related to "Google Groups: Info: How to use this forum!!"

Please add info what should be done if a reported bug is fixed, a suggested feature is added:

Who (if possible)..
- should check the new release
- set the topic to "completed"

**Comment by TonyGravagno** [comment]
Good questions. I'll ask you to ask these questions in the forum so that Dan can respond. When we have an answer I'll update the wiki and update the info page in the forum. I think this info should be available from the Getting-Help page.
