### ISSUE TITLE
Timestamp format?

### ISSUE THREAD

**Issue by otrolopezmas** [abstractspoon/ToDoList_Wiki#48]
Hi.

I am having problems understanding what kind of date format the software uses. I have discovered that 30/12/1889 would be the day 0. Is there any formula to translate a date to the program timestamp or it has to be calculated manually?

Thanks.

**Comment by Pierre-de-la-Verre** [comment]
Maybe this discussion can help to understand the logic (and the errors!) behind it:

https://autohotkey.com/boards/viewtopic.php?f=5 <https://autohotkey.com/boards/viewtopic.php?f=5&t=14007> &t=14007

**Comment by otrolopezmas** [comment]
Thank you Pierre, now I understand how it works.
