### ISSUE TITLE
show old version number when proposing update

### ISSUE THREAD

**Issue by axd1967** [abstractspoon/ToDoList_Wiki#49]
When I check for an update, I want to see what my current version is of ToDoList, so that I can decide if it's worth (or even important) to install an update, and know if I can expect much changes.

**Comment by abstractspoon** [comment]
Hi alex

This is not the place to post requests.

Please repost to our Google Group because posts here will get deleted after 7 days otherwise.

https://groups.google.com/forum/#!forum/abstractspoon-todolist-support
