### ISSUE TITLE
ToDoList insists on using IE as reporting browser

### ISSUE THREAD

**Issue by axd1967** [abstractspoon/ToDoList_Wiki#50]
My main browser is Firefox, not IE.

ToDoList should invoke whatever browser is installed rather than expect IE to be installed.

This is an old issue that has never been properly dealt with.

**Comment by abstractspoon** [comment]
Hi alex

This is not the place to post requests.

Please repost to our Google Group because posts here will get deleted after 7 days otherwise.

https://groups.google.com/forum/#!forum/abstractspoon-todolist-support
