### ISSUE TITLE
Large gap between checkbox and task title in tree view

### ISSUE THREAD

**Issue by greg221b** [abstractspoon/ToDoList_Wiki#51]
![gap](https://cloud.githubusercontent.com/assets/18467695/14535603/b02eeeae-02ad-11e6-9f84-3a6bbecdf190.png)

This large gap between checkbox and text is unsightly and should be removed.

There should be an option:  [ ]  Remove ugly gap between checkbox and text

**Comment by Pierre-de-la-Verre** [comment]
For me it is OK (Win 7 / Classic theme / Display 125%):
![zwischenablage-1](https://cloud.githubusercontent.com/assets/13277944/14536433/a3deed60-0272-11e6-99e2-34456271bb8f.png)

Have you tried with different themes and so on?

If problem still exist please consider to post it at Google Groups:
https://groups.google.com/group/abstractspoon-todolist-support.


Have you tried

**Comment by Pierre-de-la-Verre** [comment]
Closed after half a year of inactivity.
