### ISSUE TITLE
List view sorting and parent exlude.

### ISSUE THREAD

**Issue by se16n** [abstractspoon/ToDoList_Wiki#52]
Hi there!

Trying to migrate to this software, so far so good! 

But i'm faced with following issues:

1. Two projects (folders)

Project One , priority 10
Sub-task OneTask, priority 9, due date 22.08.2016

Project Two, priority 9
Sub-task TwoTask, priority 9, due date 22.08.2016

Now when i'm trying to sort it in list view by the priority i got following

OneTast
TwoTask

But i want to see it upon according parents (project) priority.
In this case Project One has bigger priority so it's should appear first.

Can it be added in program?

2. Can be parents (folders) hided from list view?

I want to view only daughter tasks.

Thanks in advance and sorry if such questions were already asked.

**Comment by abstractspoon** [comment]
Please repost to Google Groups:
https://groups.google.com/group/abstractspoon-todolist-support.
