### ISSUE TITLE
Multible time logging for one task

### ISSUE THREAD

**Issue by Strahlefz** [abstractspoon/ToDoList_Wiki#53]
I am having a question. I am having a task and want to book multiple times to the task. E.g. Task “move of hard disk”, Monday 1 hour Task is 50% done, Tuesday 2 hours task is done 100 %, in total 3 hours for the hole task. Is this possible?

**Comment by Pierre-de-la-Verre** [comment]
Hi Strahlefz

for common discussions and question I recommend to use the Google Groups:
https://groups.google.com/forum/#!forum/abstractspoon-todolist-support

But I don't understand your question - do you mean you want to edit the "Spent time" for one task?
Or to you mean "Context menu - Add Time to Task Log file"?
