### ISSUE TITLE
Analyse logged time is greyed out

### ISSUE THREAD

**Issue by Strahlefz** [abstractspoon/ToDoList_Wiki#54]
![2016-11-25 07_41_22-](https://cloud.githubusercontent.com/assets/23734418/20616494/f23ed120-b2e2-11e6-8b31-a1ede990e7ee.png)

**Comment by Pierre-de-la-Verre** [comment]
Hi Strahlefz

for common discussions and question I recommend to use the Google Groups:
https://groups.google.com/forum/#!forum/abstractspoon-todolist-support

It seems that is no Task Log file for this task list. If you start "Time Tracking" or if you add  a time, a log file will be created and both command (Show / Analyse) will be enabled.
